module.exports = {
  id: 'testfort',
  displayName: 'TestFort',
  accentColor: '#E8352A',
  accentColorHex: 0xE8352A,
  logoPath: 'assets/logos/testfort.png',
  footerLeft: null,
  footerRight: null,
  footerBrand: 'TestFort',
  website: 'testfort.com',
  email: null,
  phone: '+4 143 508 0794\n+1 310 388 93 34',
  confidentialText: 'Commercial-in-Confidence',
  decorativeCurves: false,
};
